name: sliceparamconvnext
pretrained: True
pretrained_model_name: convnext_tiny.fb_in22k  ## convnext_tiny.fb_in22k_ft_in1k, convnext_small.in12k_ft_in1k
in_dim: ~  # autofill later if None
num_classes: ~ # autofill later if None
pooling: "avg"
temperature: 0.11111
learnable_temp: False
unfreeze_last_n_layers: -1
unfreeze_first_layer: True
first_layer: reinit_as_random
reset_last_n_unfrozen_layers: False
use_auto_rgn: False
in_channel_names: ['er','golgi','membrane','microtubules','mito', 'nucleus', 'protein', 'rna']
duplicate: False
slice_class_emb: False